mblog/urls.py
from django.contrib import admin
from django.urls import path,include
from mysite.views import homepage,homepage_sorted,search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage,name='homepage'),
    path('article/',include('mysite.urls')),
    path('<str:order>',homepage_sorted,name='homepage_sorted'),
    path('search/',search,name='search'),
]

mysite/urls.py
from django.urls import path
from .views import homepage,showpost,homepage_sorted

app_name='mysite'
urlpatterns=[
    path('<str:Slug>/',showpost,name='showpost'),
]

mysite/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=200)
    number=models.IntegerField(default=0)
    slug=models.CharField(max_length=200)
    body=models.TextField()
    pub_date=models.DateTimeField(default=timezone.now)

    class Meta:
        ordering=('-pub_date',)

    def __str__(self):
        return self.title

mysite/views.py
from django.shortcuts import render,redirect
from django.template.loader import get_template
from django.http import HttpResponse
from datetime import datetime
from .models import Post
import re
# Create your views here.

def homepage(request):
    template=get_template('mysite/index.html')
    posts=Post.objects.all()
    now=datetime.now()
    html=template.render(locals())
    return HttpResponse(html)

def showpost(request,Slug):
    template=get_template('mysite/post.html')
    try:
        post=Post.objects.get(slug=Slug)
        if post:
            post.number+=1
            post.save()
            html=template.render(locals())
            return HttpResponse(html)
    except:
        return HttpResponse('ERROR:Page Not Found.')

def homepage_sorted(request,order):
    template=get_template('mysite/index.html')
    posts=Post.objects.order_by('-'+order).all()
    now=datetime.now()
    html=template.render(locals())
    return HttpResponse(html)

def search(request):
    template=get_template('mysite/index.html')
    str_list=[re.compile(x,re.I) for x in request.GET['kw'].split()]
    d={}
    for p in Post.objects.all():
        for tmp in str_list:
            if re.search(tmp,p.body):
                try:
                    d[p]+=1
                except:
                    d[p]=1
    posts=sorted(d.keys(),key=lambda a:d[a],reverse=True)
    now=datetime.now()
    html=template.render(locals())
    return HttpResponse(html)

mysite/templates/mysite/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>
        {% block title%} {% endblock %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class='container-fluid'>
        {% include 'mysite/header.html'%}
        <div class='row'>
            <div class='col-sm-4 col-md-4'>
                <div class='panel panel-default'>  
                    <div class='panel=heading'>
                        <h3>MENU</h3>
                    </div>
                    <div class='panel-body'>
                        <div class='list-group'>
                            <a href='/' class='list-group-item'>HOME</a>
                            <a href='http://tieba.baidu.com' class='list-group-item'>百度贴吧</a>
                            <a href='http://weibo.com' class='list-group-item'>新浪微博</a>
                            <a href='https://www.youtube.com' class='list-group-item'>Youtube</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class='col-sm-8 col-md-8'>
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        {% block headmmessage %}{% endblock %}
                    </div>
                    <div class='panel body'>
                        {% block content %} {% endblock %}
                    </div>
                    <div class='panel-footer'>
                        {% include 'mysite/footer.html' %}
                    </div>
                </div>
            </div>
</body>
</html>

mysite/templates/mysite/footer.html
<!-- footer.html -->
{% if now %}
<p style='font-family:微软雅黑;'>现在时刻：{{now}}</p>
{% endif %}

mysite/templates/mysite/header.html
<!-- header.html -->
{% load staticfiles %}
<div class='well' style="text-align:center;">
    <img src='{% static "images/joker.jpg" %}'><br/><br/>
    <form action='/search/' method='get'>
        <input type='text' name='kw' style="height:40px;width:600px;font-size:18pt">
        <input type='submit' value='Search' style="height:40px;width:100px">
    </form>
    <h1 style='font-family:微软雅黑;'>ㅎㅎㅎㅎㅎ</h1>
</div>

mysite/templates/mysite/home.html
<DOCTYPE html>
<html>
<head>
    <title>计算机</title>
</head>
<body>

<img src="timg.gif" width=150 height=90>
<br/>
<a href="{%url 'add2' 4 5 %}">计算 4+5</a>
<br/>
<a href="{%url 'add' %}">计算 5+6</a>

</body>
</html>

mysite/templates/mysite/index.html
<!-- index.html -->
{% extends 'mysite/base.html' %}
{% block title %}Joker's Blog{% endblock %}
{% block headmmessage %}
    <h3 style='font-family:楷体;'>Article List</h3>
    <script type="text/javascript"> 
    <!-- 
    function MM_jumpMenu(targ,selObj,restore){ //v3.0 
    eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'"); 
    if (restore) selObj.selectedIndex=0; 
    } 
    //--> 
    </script>
    <form action="" method="get"> 
        <label>Order By</label> 
        <select name="jumpMenu" id="jumpMenu" onchange="MM_jumpMenu('parent',this,0)">
            <option value="/">default</option>
            <option value="{% url 'homepage_sorted' 'number' %}">click</option> 
            <option value="{% url 'homepage_sorted' 'pub_date' %}">date</option> 
        </select> 
    </form>
{% endblock %}
{% block content %}
    {% for post in posts %}
        <div class='panel panel-default'>
            <div class='panel-heading'>
                <p style="font-family:微软雅黑;font-size:21px;font-weight:bold;">
                    <li><a href="{% url 'mysite:showpost' post.slug %}">{{post.title}}</a></li>
                </p><h6 style='font-size:12pt;'>click({{post.number}})</h6>
<!--                <p style='font-family:微软雅黑;font-size:9pt;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;'>{{post.body}}</p> -->
            </div>
            <div class='panel-footer' style='background-color:#efefef'>
                <p>
                    Released date:{{ post.pub_date }}
                </p>
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

mysite/templates/mysite/post.html
<!-- post.html -->
{% extends 'mysite/base.html' %}
{% load markdown_deux_tags %}
{% block title %}{{post.title}}-Sub{% endblock%}
{% block headmmessage %}
    <h3 style='font-family:微软雅黑;'>{{post.title}}</h3>
    <a style='font-family:微软雅黑;' href='/'>回首页</a>
{% endblock %}
{% block content %}
        <p style='font-family:微软雅黑;font-size:12pt;letter-spacing:2pt;'>
        {{post.body|markdown}}
        </p>
{% endblock %}